// clients/client-angular/src/app/modules/contact/components/contact-item/contact-item.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ContactsStateModel } from '../../models/contacts-state.model';

@Component({
  selector: 'app-contact-item',
  templateUrl: './contact-item.component.html',
  styleUrls: ['./contact-item.component.scss']
})
export class ContactItemComponent implements OnInit {
  @Input() contact: ContactsStateModel;
  constructor() { }

  ngOnInit() {
    console.log(this.contact);
  }
  makeUpperCase(text: string) {
    return text.charAt(0).toUpperCase() + text.slice(1)
  }

}

<div class="card bg-light">
  <h3 class="text-primary text-left">
    {{ contact.name }}
    <span
      class="badge"
      [ngStyle]="{ float: 'right' }"
      [ngClass]="{
        'badge-success': contact.type === 'professional',
        'badge-primary': contact.type !== 'professional'
      }"
      >{{ makeUpperCase(contact.type) }}</span
    >
  </h3>
  <ul class="list">
    <li *ngIf="contact.email">
      <i class="fas fa-envelope-open"></i> {{ contact.email }}
    </li>
    <li *ngIf="contact.phone">
      <i class="fas fa-phone"></i> {{ contact.phone }}
    </li>
  </ul>
  <p>
    <button class="btn btn-dark btn-sm">Edit</button>
    <button class="btn btn-danger btn-sm">Delete</button>
  </p>
</div>

// clients/client-react/src/components/contacts/ContactItem.js
import React from 'react';
import PropTypes from 'prop-types';

export const ContactItem = ({ contact }) => {
  const { _id, name, email, phone, type } = contact;
  return (
    <div className='card bg-light'>
      <h3 className='text-primary text-left'>
        {name}{' '}
        <span
          style={{ float: 'right' }}
          className={
            'badge ' +
            (type === 'prefessional' ? 'badge-success' : 'badge-primary')
          }
        >
          {type.charAt(0).toUpperCase() + type.slice(1)}
        </span>
      </h3>
      <ul className='list'>
        {email && (
          <li>
            <i className='fas fa-envelope-open'></i> {email}
          </li>
        )}
        {phone && (
          <li>
            <i className='fas fa-phone'></i> {phone}
          </li>
        )}
      </ul>
      <p>
        <button className='btn btn-dark btn-sm'>Edit</button>
        <button className='btn btn-danger btn-sm'>Delete</button>
      </p>
    </div>
  );
};
ContactItem.propTypes = {
  contact: PropTypes.object.isRequired,
};
export default ContactItem;
